apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: devops-tech-test
spec:
  selector:
    app: devops-tech-test-api-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
