apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/mithunraj-mithu/noosphere-bootstrap-mithun
    newName: ghcr.io/mithunraj-mithu/noosphere-bootstrap-mithun
    newTag: "027a31dd0a340274c9742d9e2bd33208db67f399"
replicas:
  - name: ap√≠-deployment
    count: 1
