apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/mithunraj-mithu/noosphere-bootstrap-mithun
    newName: ghcr.io/mithunraj-mithu/noosphere-bootstrap-mithun
    newTag: "b2d84be"
replicas:
  - name: ap√≠-deployment
    count: 1
