apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -dev


labels:
  - pairs:
      env: dev
    includeSelectors: true

images:
- name: nginx # Will look for container with image name nginx
  newName: nginx
  newTag: "latest"